name: KetchupStats
version: '1.0'
main: dev.rajce.ketchupStats.KetchupStats
api-version: '1.21'
authors: [ Lupino1 ]
description: Simple plugin for creating custom stats
softdepend:
  - PlaceholderAPI

commands:
  ketchupstats:
    permission: ketchupstats.command



permissions:
  ketchupstats.command:
    default: op
  ketchupstats.commands.createstat:
    default: op
  ketchupstats.commands.reload:
    default: op
  ketchupstats.commands.set:
    default: op
  ketchupstats.commands.get:
    default: op
  ketchupstats.commands.give:
    default: op
  ketchupstats.commands.take:
    default: op
  ketchupstats.commands.deletestat:
    default: op
  ketchupstats.admin:
    default: op